config/routes.rb
Rails.application.routes.draw do

  root to: 'items#index'
  devise_for :users,
  controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'mypage/identification', action: :edit, controller: 'identification'
  get 'mypage/profile', action: :edit, controller: 'profile'
  get "logout" => "profile#logout"
  get 'mypage' => 'profile#mypage'
  resources :items, only: [:index,:new,:show,:create,:edit,:update,:destroy] do
    get 'buy', on: :member #on: :memberでidをURLに表示させる。そのidを元にparams[:id]で情報をテーブルから引き出す。
    post 'pay', on: :member
    collection do
      get 'search'
      get 'done', to: 'items#done'
      get 'ladies'
      get 'mens'
      get 'appliances'
      get 'hobby'
      get 'chanel'
      get 'louis_vuitton'
      get 'supreme'
      get 'nike'
    end
  end

  #ユーザー各種新規登録画面
  get "signup", to: "signup#index"
  resources :signup do
    collection do
      get 'registration' #新規会員登録入力画面（userテーブルに登録したい情報）
      post 'sms_confirmation' #携帯電話番号の入力（addressテーブルに登録したい情報）
      post 'address'   #お届け先住所の入力（addressテーブルに登録したい情報）最後の入力ページ
      post 'credit_card'  #クレジットカード
      get 'done' #登録完了
    end
  end

  #マイページのお支払い方法
  resources :card, only: [:new, :show] do
    collection do
      get 'add_card', to: 'card#add_card'
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  get "categories", to: "categories#index"

  get '/jquerytest/test' => 'jquerytest#test' #jquery動作確認のためのページ
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  require "payjp"

  before_action :validate_registration, only: :sms_confirmation #sms_confirmationに行く前にregistrationのバリデーションチェック
  before_action :validate_sms_confirmation, only: :address #addressに行く前にsms_confirmationのバリデーションチェック
  before_action :validate_address, only: :credit_card #credit_cardに行く前にaddressのバリデーションチェック
  
  def index
  end

  def registration
    @user = User.new
  end

  # registrationバリデーション
  def validate_registration
    session[:user_params_registration] = user_params #registrationで入力したuserモデルに関する情報

    if session[:sns].present? ##sns認証の場合(もしsnsのproviderとuidを取得したsessionがあったら)

      password = Devise.friendly_token(7) #7桁のパスワードを自動作成
      session[:user_params_registration][:password] = password #作成したパスワードをsession[:user_params_registration]のpasswordに渡す
      session[:user_params_registration][:password_confirmation] = password #作成したパスワードをsession[:user_params_registration]のpassword_confirmationに渡す

      @user = User.new(nickname: session[:user_params_registration][:nickname],
      email: session[:user_params_registration][:email],
      password: session[:user_params_registration][:password],
      password_confirmation: session[:user_params_registration][:password_confirmation],
      last_name: session[:user_params_registration][:last_name],
      first_name: session[:user_params_registration][:first_name],
      last_name_kana: session[:user_params_registration][:last_name_kana],
      first_name_kana: session[:user_params_registration][:first_name_kana],
      birth_year: session[:user_params_registration][:birth_year],
      birth_month: session[:user_params_registration][:birth_month],
      birth_day: session[:user_params_registration][:birth_day],
      #userモデルのバリデーションを通過するための仮置き
      phone_number: '09012341234')

    else #メールアドレスで新規登録する場合
    @user = User.new(nickname: session[:user_params_registration][:nickname],
                     email: session[:user_params_registration][:email],
                     password: session[:user_params_registration][:password],
                     password_confirmation: session[:user_params_registration][:password_confirmation],
                     last_name: session[:user_params_registration][:last_name],
                     first_name: session[:user_params_registration][:first_name],
                     last_name_kana: session[:user_params_registration][:last_name_kana],
                     first_name_kana: session[:user_params_registration][:first_name_kana],
                     birth_year: session[:user_params_registration][:birth_year],
                     birth_month: session[:user_params_registration][:birth_month],
                     birth_day: session[:user_params_registration][:birth_day],
                     #userモデルのバリデーションを通過するための仮置き
                     phone_number: '09012341234')
    end

    # できたら覚書として残したいです。
    # session[:user_params_registration]) #もしregistrationがaddressモデルと関連づけていたらsession[:user_params_registration]の中身はこうなっている。
    # @user.build_address(last_name: session[:user_params][:address_attributes][:last_name],
    #                     first_name: session[:user_params][:address_attributes][:first_name],
    #                     last_name_kana: session[:user_params][:address_attributes][:last_name_kana],
    #                     first_name_kana: session[:user_params][:address_attributes][:first_name_kana],
    #                     birth_year: session[:user_params][:address_attributes][:birth_year],
    #                     birth_month: session[:user_params][:address_attributes][:birth_month],
    #                     birth_day: session[:user_params][:address_attributes][:birth_day],

    render '/signup/registration' unless @user.valid? #失敗した時のビュー呼び出しはroutesを通さないrenderを使う。routeを通すと再度アクションが動いてページが更新されて入力値が消えてしまうため。
  end

  def sms_confirmation
    @user = User.new
  end

  # sms_confirmationバリデーション
  def validate_sms_confirmation
    session[:user_params_sms_confirmation] = user_params #sms_confirmationで入力された情報
    session[:user_params_sms_confirmation].merge!(session[:user_params_registration]) #registrationで入力した情報を今回の入力内容に加える
    
    @user = User.new(nickname: session[:user_params_sms_confirmation][:nickname],
                     email: session[:user_params_sms_confirmation][:email],
                     password: session[:user_params_sms_confirmation][:password],
                     password_confirmation: session[:user_params_sms_confirmation][:password_confirmation],
                     last_name: session[:user_params_sms_confirmation][:last_name],
                     first_name: session[:user_params_sms_confirmation][:first_name],
                     last_name_kana: session[:user_params_sms_confirmation][:last_name_kana],
                     first_name_kana: session[:user_params_sms_confirmation][:first_name_kana],
                     birth_year: session[:user_params_sms_confirmation][:birth_year],
                     birth_month: session[:user_params_sms_confirmation][:birth_month],
                     birth_day: session[:user_params_sms_confirmation][:birth_day],
                     phone_number: session[:user_params_sms_confirmation][:phone_number])

    render '/signup/sms_confirmation' unless @user.valid?
  end


  def address
    @user = User.new
    @user.build_address
  end

  #addressバリデーション
  def validate_address
    session[:address_attributes_after_address] = user_params[:address_attributes]
    
    @user = User.new(session[:user_params_sms_confirmation]) #validate_sms_confirmationと同じ中身
    @user.build_address(session[:address_attributes_after_address]) #中身はaddressで入力した情報
    
    render '/signup/address' unless @user.valid?
  end

  def credit_card
    @user = User.new
    @user.build_card
  end

  def create
    @user = User.new(session[:user_params_sms_confirmation]) #step1のuserモデルに関する情報が入ったsessionを渡す。userテーブルに情報を保存する。
    @user.build_address(session[:address_attributes_after_address]) #addressテーブルに情報を保存する。 #このあとに@user.buidl_address(sessionでもuser_paramsでも)と書いてしまうと同じ名前=上書きされるので必ずmergeすること
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY] #テスト秘密鍵の環境変数
    
    if params['payjp-token'].blank? #pyajp-tokenが空または存在しないか判定している（blank?はnilと空のオブジェクトを判定できる）
      redirect_to credit_card_signup_index_path
    else
      customer = Payjp::Customer.create(card: params['payjp-token'])
      @user.build_card(customer_id: customer.id, card_id: customer.default_card)

    #sns認証の場合（snsから取得したuid、providerが入ったsessionが存在していたら）
    if session[:sns].present?
      @user.save
      SnsCredential.create(user_id: @user.id,uid: session[:sns]["uid"],provider: session[:sns]["provider"]) #snsから取得したuid,providerをuser_idを足がかりにしてsns_credentialテーブルに保存する
      session[:id] = @user.id #user_idをsessionに入れてログイン状態にする。
      redirect_to done_signup_index_path #登録完了ページにとぶ

    #メールアドレスで新規登録する場合
    elsif @user.save
      redirect_to done_signup_index_path #登録完了画面に飛ぶ。
      session[:id] = @user.id #user_idをsessionに入れてログイン状態にする。

    #登録できなかった場合
    else
      ender 'signup/registration' #registrationに飛ぶ。
    end
  end
end


  def done #登録完了ページ ログイン状態を継続する
    sign_in User.find(session[:id]) unless user_signed_in?
  end

  private
  def user_params #registration~credit_cardでユーザーが入力した項目のうちDBに登録したい項目
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :last_name, :first_name, :last_name_kana, :first_name_kana, :birth_year, :birth_month, :birth_day, :phone_number, address_attributes: [:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_cord, :prefecture_id, :city, :block, :building, :phone_number], card_attributes:[:customer_id, :card_id])
  end

end

app/views/signup/_error_message.html.haml
.signup_form_error_message
  - if user.errors.any?
    - unless user.valid?
      - if errors = user.errors.full_messages_for(column.to_sym) #to_symは文字列をシンボル型にする。:sampleなど「:と文字」で表す。ハッシュのキーやインスタンスに使われる。
        %ul
          - errors.each do |error|
            %li=error

app/views/signup/address.html.haml
.member-new-address-wrapper
  .member-new-address-header
    .sms-confirmation-merukari-logo
      = image_tag "merikari4.png", size:'185x49',class: "confirmation_merukari"
    .member-new-address-progress
      %li.progress
        会員情報
        .progress-parts_1
      %li.progress
        電話番号認証
        .progress-parts_complete
      %li.progress-here
        お届け先住所入力
        .progress-parts_here
      %li.progress
        支払い方法
        .progress-parts
      %li.progress
        完了
        .progress-parts_5
  .member-new-address-menu
    .member-new-address-menu__contents
      .member-new-address-menu__top
        発送元・お届け先住所入力
      .member-new-address-menu__main
        .member-new-address-menu__input-field
          = form_for @user, url: credit_card_signup_index_path, method: :post do |f|
            = hidden_field_tag :current_step, 'address'
            = f.fields_for :address do |a| #addressに保存する
              .member-new-name-kanji
                %label.label-1 お名前
                %span.span-1 必須
                = a.text_field :last_name, placeholder: '例) 山田', class: 'input-registration-form'
                = render partial: 'signup/error_message', locals: {user: @user, column: 'address.last_name'}
                = a.text_field :first_name, placeholder: '例) 彩', class: 'input-registration-form'
                = render partial: 'signup/error_message', locals: {user: @user, column: 'address.first_name'}
              .member-new-name-kana
                %label.label-1 お名前カナ
                %span.span-1 必須
                = a.text_field :last_name_kana, placeholder: '例) ヤマダ', class: 'input-registration-form'
                = render partial: 'signup/error_message', locals: {user: @user, column: 'address.last_name_kana'}
                = a.text_field :first_name_kana, placeholder: '例) アヤ', class: 'input-registration-form'
                = render partial: 'signup/error_message', locals: {user: @user, column: 'address.first_name_kana'}
              .member-new-postal-code
                %label.label-1 郵便番号
                %span.span-1 必須
                = a.text_field :postal_cord, placeholder: '例)123-4567', class: 'input-registration-form'
                = render partial: 'signup/error_message', locals: {user: @user, column: 'address.postal_cord'}
              .member-new-prefectures
                %label.label-1 都道府県
                %span.span-1 必須
                = a.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt: "---"}
                = render partial: 'signup/error_message', locals: {user: @user, column: 'address.prefecture_id'}
              .member-new-municipal-district
                %label.label-1 市町村区
                %span.span-1 必須
                = a.text_field :city, placeholder: '例)横浜市緑区', class: 'input-registration-form'
                = render partial: 'signup/error_message', locals: {user: @user, column: 'address.city'}
              .member-new-banchi
                %label.label-1 番地
                %span.span-1 必須
                = a.text_field :block, placeholder: '例)青山1-1-1', class: 'input-registration-form'
                = render partial: 'signup/error_message', locals: {user: @user, column: 'address.block'}
              .member-new-building-name
                %label.label-1 建物名
                %span.span-2 任意
                = a.text_field :building, placeholder: '例)柳ビル103', class: 'input-registration-form'
                = render partial: 'signup/error_message', locals: {user: @user, column: 'address.building'}
              .member-new-telephone-number
                %label.label-1 電話番号
                %span.span-2 任意
                = a.text_field :phone_number, placeholder: '例)09012345678', class: 'input-registration-form'
                = render partial: 'signup/error_message', locals: {user: @user, column: 'address.phone_number'}
            = f.submit '次に進む', class: :"button-next-page"
  = render "devise/registrations/footer-signup" 

app/views/signup/credit_card.html.haml
.member-new-credit-card-wrapper
  .member-new-credit-card-header
    .sms-confirmation-merukari-logo
      = image_tag "merikari4.png", size:'185x49',class: "confirmation_merukari"
    .member-new-credit-card-progress
      %li.progress
        会員情報
        .progress-parts_1
      %li.progress
        電話番号認証
        .progress-parts_complete
      %li.progress
        お届け先住所入力
        .progress-parts_complete
      %li.progress-here
        支払い方法
        .progress-parts_here
      %li.progress
        完了
        .progress-parts_5
  .member-new-credit-card-menu
    .member-new-credit-card-menu__contents
      .member-new-credit-card-menu__top
        支払い方法
      .member-new-credit-card-menu__main
        = form_tag(signup_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
          .member-new-credit-card-menu__input-field
            %label.label-1 カード番号
            %span.span-1 必須
            = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            %ul.credit-card-type-icon
              %li.credit-card-type-icon__list1
                = image_tag "visa.png", size:'48x28', class: "visa-icon"
              %li.credit-card-type-icon__list
                = image_tag "master.png", size:'40x23', class: "master-icon"
              %li.credit-card-type-icon__list
                = image_tag "saisoncard.png", size:'30x20', class: "saison-icon"
              %li.credit-card-type-icon__list
                = image_tag "jcb.png", size:'32x20', class: "jcb-icon"
              %li.credit-card-type-icon__list
                = image_tag "amex.png", size:'21x20', class: "american-ex-icon"
              %li.credit-card-type-icon__list
                = image_tag "diners.png", size:'32x20', class: "diners-icon"
              %li.credit-card-type-icon__list
                = image_tag "discover.png", size:'32x20', class: "discover-icon"
            .new-credit-card-expiration-date
              %label.label-1 有効期限
              %span.span-1 必須
              .expiration-date-month-day
                .new-credit-card-expiration-month
                %select#exp_month{name: "exp_month", type: "text"}
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                %span 月
                .new-credit-card-expiration-year
                %select#exp_year{name: "exp_year", type: "text"}
                  %option{value: ""} --
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                %span 年
                %br
              .new-credit-card-code-form
              %label.label-1 セキュリティコード
              %span.span-1 必須
              = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              .card-back-side
                .card-back-side__text
                  %span.card-back-side__question
                    ?
                  .card-back-side__question-text
                    カード裏面の番号とは？
          #card_token
          = submit_tag "次に進む", id: "token_submit", class: "button-next-page"

  = render "devise/registrations/footer-signup" 

app/views/signup/done.html.haml
.member-all-done-wrapper
  .member-all-done-header
    .sms-confirmation-merukari-logo
      = image_tag "merikari4.png", size:'185x49',class: "confirmation_merukari"
    .member-all-done-progress
      %li.progress
        会員情報
        .progress-parts_1
      %li.progress
        電話番号認証
        .progress-parts_complete
      %li.progress
        お届け先住所入力
        .progress-parts_complete
      %li.progress
        支払い方法
        .progress-parts_complete
      %li.progress-here
        完了
        .progress-parts_5
  .member-all-done-menu
    .member-all-done-menu__contents
      .member-all-done-menu__top
        会員登録完了 
      .member-all-done-menu__main
        .member-all-done-menu__text
          %li ありがとうございます。
          %li 会員登録が完了しました。
        .member-all-done-menu__button
          = link_to 'メルカリをはじめる', root_path, class: "default_btn_red"
      .member-all-done-menu__banner
        .member-all-done-menu__banner__container
          .member-all-done-menu__banner__container--left
            .all-done-menu-first_title
              スマホでかんたんフリマアプリ
            .second_title
              今すぐ無料ダウンロード！
            .icons
              .mercai_icon
                = image_tag 'mercari_squar.png', size:'48x48', class: 'mercari_icon'
              .app
                = image_tag 'apple.png', size:'140x40', class: 'app'
              .google
                = image_tag 'google.png', size:'140x40', class: 'google'
          .member-all-done-menu__banner__container--right
            .image
              = image_tag "banner_free.png", size:'300x260', class: 'image'
              
  = render "devise/registrations/footer-signup" 

app/views/signup/index.html.haml
%head
  %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/

.sign-up
  = render 'devise/registrations/header-signup'
  .sign-in
    .sign-in-menu
      .menu-title
        新規会員登録
      .btn-menu
        = link_to 'メールアドレスで登録する', registration_signup_index_path, method: :get, class: "sign-in__btn sign-in__btn--mail"
        %i.material-icons.white mail_outline
        = link_to user_facebook_omniauth_authorize_path, method: :post, class: "sign-in__btn sign-in__btn--facebook" do
          = fa_icon 'facebook-square', class: "facebook-icon"
          Facebookで登録する
        = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: "sign-in__btn sign-in__btn--google" do
          = image_tag "google-icon.png", size:'50x50', class: "google-icon"
          Googleで登録する
  = render 'devise/registrations/footer-signup'

app/views/signup/registration.html.haml
.member-registration-wrapper
  .member-registration-header
    .registration-merukari-logo
      = image_tag "merikari4.png", size:'185x49',class: "my_merukari"
    .member-registration-progress
      %li.progress-here
        会員情報
        .progress-parts_1
      %li.progress
        電話番号認証
        .progress-parts
      %li.progress
        お届け先住所入力
        .progress-parts
      %li.progress
        支払い方法
        .progress-parts
      %li.progress
        完了
        .progress-parts_5
  .member-registration-menu
    %h2.member-registration-menu__top
      会員情報入力

    .member-registration-menu__form
      .form-menu
        = form_for @user, url: sms_confirmation_signup_index_path, html: {id: :new_user} do |f|
          = hidden_field_tag :current_step, 'registration'
          .member-nickname
            %label.label-1 ニックネーム
            %span.span-1 必須
            = f.text_field :nickname, placeholder: '例) メルカリ太郎', class: 'input-registration-form'
            = render partial: 'signup/error_message', locals: {user: @user, column: 'nickname'}
          .member-mail
            %label.label-1 メールアドレス
            %span.span-1 必須
            = f.email_field :email, placeholder: 'PC・携帯どちらでも可', class: 'input-registration-form'
            = render partial: 'signup/error_message', locals: {user: @user, column: 'email'}
          .member-password
            - if @sns.present?
            - else
              %label.label-1 パスワード
              %span.span-1 必須
              = f.password_field :password, placeholder: '7文字以上', class: 'input-registration-form'
              = render partial: 'signup/error_message', locals: {user: @user, column: 'password'}
          .re-member-password
            - if @sns.present?
            - else
              %label.label-1 パスワード(確認)
              %span.span-1 必須
              = f.password_field :password_confirmation, placeholder: '7文字以上', class: 'input-registration-form'
              = render partial: 'signup/error_message', locals: {user: @user, column: 'password_confirmation'}  
          .registration-identification
            %h3 本人確認
            %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客様に公開されることはありません。

          .identification-name-kanji
            %label.label-1 お名前(全角)
            %span.span-1 必須
            = f.text_field :last_name, placeholder: '例) 山田', class: 'input-kanji-myouji'
            = f.text_field :first_name, placeholder: '例) 彩', class: 'input-kanji-name'
            .error-messages_kanji
              = render partial: 'signup/error_message', locals: {user: @user, column: 'last_name'}
              = render partial: 'signup/error_message', locals: {user: @user, column: 'first_name'}
          .identification-name-kana
            %label.label-1 お名前カナ(全角)
            %span.span-1 必須
            = f.text_field :last_name_kana, placeholder: '例) ヤマダ', class: 'input-kana-myouji'
            = f.text_field :first_name_kana, placeholder: '例) アヤ', class: 'input-kana-name'
          .error-messages_kana
            = render partial: 'signup/error_message', locals: {user: @user, column: 'last_name_kana'}
            = render partial: 'signup/error_message', locals: {user: @user, column: 'first_name_kana'}
          .identification-birthday
            %label.label-1 生年月日
            %span.span-1 必須
            .birth_select_form
              = f.select :birth_year, [["2000", "2000"], ["1999", "1999"], ["1998", "1998"], ["1997", "1997"], ["1996", "1996"], ["1995", "1995"], ["1994", "1994"], ["1993", "1993"], ["1992", "1992"], ["1991", "1991"], ["1990", "1990"], ["1989", "1989"], ["1988", "1988"], ["1987", "1987"], ["1986", "1986"], ["1985", "1985"], ["1984", "1984"], ["1983", "1983"], ["1982", "1982"], ["1981", "1981"], ["1980", "1980"], ["1979", "1979"], ["1978", "1978"], ["1977", "1977"], ["1976", "1976"], ["1975", "1975"], ["1974", "1974"], ["1973", "1973"], ["1972", "1972"], ["1971", "1971"], ["1970", "1970"]], {prompt: "---"}, class: "select-default_year select-text-default"
              %span.span_year 年
              = f.select :birth_month, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"], ["7", "7"], ["8", "8"], ["9", "9"], ["10", "10"], ["11", "11"], ["12", "12"]],  {prompt: "---"}, class: "select-default_month select-text-default"
              %span.span_month 月
              = f.select :birth_day, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"], ["7", "7"], ["8", "8"], ["9", "9"], ["10", "10"], ["11", "11"], ["12", "12"], ["13", "13"], ["14", "14"], ["15", "15"], ["16", "16"], ["17", "17"], ["18", "18"], ["19", "19"], ["20", "20"], ["21", "21"], ["22", "22"], ["23", "23"], ["24", "24"], ["25", "25"], ["26", "26"], ["27", "27"], ["28", "28"], ["29", "29"], ["30", "30"], ["31", "31"]], {prompt: "---"}, class: "select-default_day select-text-default"
              %span.span_day 日
              .error-messages_birth
                = render partial: 'signup/error_message', locals: {user: @user, column: 'birth_year'}
                = render partial: 'signup/error_message', locals: {user: @user, column: 'birth_month'}
                = render partial: 'signup/error_message', locals: {user: @user, column: 'birth_day'}
          %p.identification-comments
            ※本人確認情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          .no-robot
            %input.no-robot-check{:name => "check", :type => "checkbox"}/          
            %a 私はロボットではありません
            = image_tag "logo_recaptcha.png", size:'30x30', class: "logo_recaptcha"
            .no-robot-text
              %li reCAPTCHA
              %li プライバシー-利用規約
          %p.consent-text
            「次へ進む」のボタンを押すことにより、
            %a.consent-link{:href => "https://www.mercari.com/jp/tos_list/"}> 利用規約
            に同意したものとみなします
          = f.submit "次へ進む", class: :"button-next-page"        
        .personal-information-page-jump
          本人情報の登録について
          %i.yajirusi-next-page

  = render "devise/registrations/footer-signup" 

app/views/signup/sms.html.haml
.member-sms-wrapper
  .member-sms-confirmation-header
    .sms-confirmation-merukari-logo
      = image_tag "merikari4.png", size:'185x49',class: "confirmation_merukari"
    .member-sms-confirmation-progress
      %li.progress
        会員情報
        .progress-parts_1
      %li.progress-here
        電話番号認証
        .progress-parts_here
      %li.progress
        お届け先住所入力
        .progress-parts
      %li.progress
        支払い方法
        .progress-parts
      %li.progress
        完了
        .progress-parts_5
  .member-mobile-number-menu
    .member-mobile-number-menu__contents
      .member-mobile-number-menu__top
        電話番号認証
      .member-mobile-number-menu__first
        .member-mobile-number-menu__main
          .member-mobile-number-menu__form
            %label 認証番号
            %input.input-sms-mobile-number{ name: "number", placeholder: "認証番号を入力", type: "text", value: ""}/
            %p SMSで届いた認証番号を入力してください
          .form-input-complete-button
            認証して完了
        .not-sms-number
          .not-sms-number__text
            %label 30秒たっても認証番号が届かない方へ
            %p.to-call 電話で認証番号を聞くこともできます。
          .not-sms-number__button
            電話で認証番号を聞く（通話無料）
        .one-more-mobile-number
          .one-more-mobile-number__text
            %label 認証番号を再送することもできます。もう一度電話番号を入力して下さい。
          .input-number-link
            = link_to '電話番号を再度入力する', "https://www.mercari.com/jp/"
          %p.consent-message 
            ※SMSが届かない場合は
            =link_to 'SMS受信設定', "https://www.mercari.com/jp/"
            を確認して、もう一度電話番号を入力してください。

  = render "devise/registrations/footer-signup" 

app/views/signup/sms_confirmation.html.haml
.member-sms-confirmation-wrapper
  .member-sms-confirmation-header
    .sms-confirmation-merukari-logo
      = image_tag "merikari4.png", size:'185x49',class: "confirmation_merukari"
    .member-sms-confirmation-progress
      %li.progress
        会員情報
        .progress-parts_1
      %li.progress-here
        電話番号認証
        .progress-parts_here
      %li.progress
        お届け先住所入力
        .progress-parts
      %li.progress
        支払い方法
        .progress-parts
      %li.progress
        完了
        .progress-parts_5
  .member-sms-confirmation-menu
    = form_for @user, url: address_signup_index_path do |f|
      = hidden_field_tag :current_step, 'sms_confirmation'
      .member-sms-confirmation-menu__contents
        %h2.member-sms-confirmation-menu__top
          電話番号の確認
        .member-sms-confirmation-menu__form
          .member-mobile_number
            %label 携帯電話の番号(ハイフンはいりません)
            = f.text_field :phone_number, placeholder: '携帯電話の番号を入力', class: 'input-registration-form'
            = render partial: 'signup/error_message', locals: {user: @user, column: 'phone_number'}
            %p 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
          = f.submit 'SMSを送信する', class: :"member-sms-confirmation-menu_button"
          %br
          %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
          .mobile-explanation-link
            電話番号の確認が必要な理由
            %i.yajirusi-next-page
  = render "devise/registrations/footer-signup" 