config/routes.rb
Rails.application.routes.draw do

  root to: 'items#index'
  devise_for :users,
  controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'mypage/identification', action: :edit, controller: 'identification'
  get 'mypage/profile', action: :edit, controller: 'profile'
  get "logout" => "profile#logout"
  get 'mypage' => 'profile#mypage'
  resources :items, only: [:index,:new,:show,:create,:edit,:update,:destroy] do
    get 'buy', on: :member #on: :memberでidをURLに表示させる。そのidを元にparams[:id]で情報をテーブルから引き出す。
    post 'pay', on: :member
    collection do
      get 'search'
      get 'done', to: 'items#done'
      get 'ladies'
      get 'mens'
      get 'appliances'
      get 'hobby'
      get 'chanel'
      get 'louis_vuitton'
      get 'supreme'
      get 'nike'
    end
  end

  #ユーザー各種新規登録画面
  get "signup", to: "signup#index"
  resources :signup do
    collection do
      get 'registration' #新規会員登録入力画面（userテーブルに登録したい情報）
      post 'sms_confirmation' #携帯電話番号の入力（addressテーブルに登録したい情報）
      post 'address'   #お届け先住所の入力（addressテーブルに登録したい情報）最後の入力ページ
      post 'credit_card'  #クレジットカード
      get 'done' #登録完了
    end
  end

  #マイページのお支払い方法
  resources :card, only: [:new, :show] do
    collection do
      get 'add_card', to: 'card#add_card'
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  get "categories", to: "categories#index"

  get '/jquerytest/test' => 'jquerytest#test' #jquery動作確認のためのページ
end

app/models/item.rb
class Item < ApplicationRecord

  has_many_attached :images
  belongs_to :user, optional: true
  has_many :likes
  has_one :order

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  #ここから出品ページでのアソシエーション
  has_many :items_categories
  has_many :categories, through: :items_categories

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  require 'payjp'

  before_action :authenticate_user!, only: [:edit, :update, :destory, :buy, :pay]

  def index

    @items = Item.all.order("created_at DESC").limit(10)

    #人気カテゴリー
    @ladies = Item.where(category_parent: 1).order("created_at DESC").limit(10) #itemテーブルからcategory_parentが1（レディース）のアイテムを取得して@ladiesに渡す
    @mens = Item.where(category_parent: 139).order("created_at DESC").limit(10) #itemテーブルからcategory_parentが139（メンズ）のアイテムを取得して@mensに渡す
    @hobby = Item.where(category_parent: 579).order("created_at DESC").limit(10) #itemテーブルからcategory_parentが579(おもちゃ)のアイテムを取得して@hobyに渡す
    @appliances = Item.where(category_parent: 784).order("created_at DESC").limit(10) #itemテーブルからcategory_parentが784(家電)のアイテムを取得して@home_appliancesに渡す

    #人気ブランド
    @chanel = Item.where(brand: "シャネル").order("created_at DESC").limit(10)
    @louis_vuitton = Item.where(brand: "ルイヴィトン").order("created_at DESC").limit(10)
    @supreme = Item.where(brand: "シュプリーム").order("created_at DESC").limit(10)
    @nike = Item.where(brand: "ナイキ").order("created_at DESC").limit(10)

  end

  
  def ladies
    @ladies = Item.where(category_parent: 1).order("created_at DESC")
  end

  def mens
    @mens = Item.where(category_parent: 139).order("created_at DESC")
  end

  def appliances
    @appliances = Item.where(category_parent: 784).order("created_at DESC")
  end

  def hobby
    @hobby = Item.where(category_parent: 579).order("created_at DESC").limit(10)
  end

  def chanel
    @chanel = Item.where(brand: "シャネル").order("created_at DESC")
  end

  def louis_vuitton
    @louis_vuitton = Item.where(brand: "ルイヴィトン").order("created_at DESC")
  end

  def supreme
    @supreme = Item.where(brand: "シュプリーム").order("created_at DESC")
  end

  def nike
    @nike = Item.where(brand: "ナイキ").order("created_at DESC")
  end


  def new
    @items = Item.new
    @parents = Category.where(ancestry: nil).order("id ASC").limit(13)
  end

  def search
    if params[:parent_id]
      @children = Category.find(params[:parent_id]).children
    # 親カテゴリーのidから子カテゴリーのidの配列を作成してインスタンス変数で定義
    else
      @grandchildren = Category.find(params[:child_id]).children
    # 子カテゴリーのidから孫カテゴリーのidの配列を作成してインスタンス変数で定義
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @items = Item.new(item_params)
    if @items.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @items = Item.find(params[:id])
    @shipment_area_data = Prefecture.find_by(id: @items.shipment_area) #@shipment_areaのidで@Prefectureモデルから該当の都道府県を探して@shipment_area_dataに渡す
    @shipment_area_name = @shipment_area_data.name #Prefectureモデルから見つけた都道府県の名前だけを@shipment_area_nameに渡す
    @user = User.find(@items.seller_id) #seller_idと同じidをUserモデルから探して@userに渡す
    @category_parent = Category.find_by(id: @items.category_parent)
    @category_parent_name = @category_parent.name
  end

  def edit
    @items = Item.find(params[:id])
    @parents = Category.where(ancestry: nil).order("id ASC").limit(13)
  end

  def update 
    @items = Item.find(params[:id]) #もともと登録されていた商品情報(itemモデル分)
    @user = User.find(@items.seller_id)
    if delete_params[:image_id].present? #editからparams[:image_id]が送られてきたら以下の処理を行う
      @delete_params = delete_params[:image_id]
      @active = @items.images.find(@delete_params)
      @active.each do |active|
        active.purge
      end
    end

    if @items.update(item_params) #editで入力した編集情報で@itemを更新する
      redirect_to action: 'show'
    else
      render :edit
    end
  end

  def destroy
    @items = Item.find(params[:id]) #URLのitem_idのデータを取り出して@itemsに渡す
    @user = User.find(@items.seller_id)
    if @items.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def buy
    @items = Item.find(params[:id]) #URLのidと同じitem_idの情報をitemモデルから取り出して@itemsに入れる。
    #画像表示
    @items_id = @items.id #@itemsのitem_idだけ取り出して@items_idに渡す

    #購入者情報
    @buyer = Address.find_by(user_id: current_user.id) #購入者の配送先住所を取得する
    @buyer_prefecrure = Prefecture.find_by(id: @buyer.prefecture_id) #@buyerのprefecture_idでPrefectureモデルから都道府県のidとnameを引っ張る
    @prefecture_name = @buyer_prefecrure.name #@buyer_prefecuture.nameで都道府県名だけにして@prefecture_nameに渡す
    
    #クレジットカード情報
    card = Card.where(user_id: current_user.id).first #cardテーブルから現在ログインしているユーザーのidのuser_idをcardに入れる id,user_id,customer_id,card_idが入っている。
    if card.blank? #テーブルに登録されたカード情報がなければ
      redirect_to controller: "card", action: "new" #card_controllerのnewアクションにとぶ（カード登録画面）
    else #該当のカード情報がある場合
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY] #Payjpの秘密鍵(credential.ymlに保存している)

      #Payjpに登録してある顧客情報を秘密鍵でひっぱってくる
      customer = Payjp::Customer.retrieve(card.customer_id) #Payjpの顧客情報が入っている。
      @default_card_information = customer.cards.retrieve(card.card_id) #buy.html.hamlに表示させるカード情報を@default_card_informationに入れる
  end
end

  def pay #支払い
    @items = Item.find(params[:id]) #URLのidとitemテーブルのidが同じ情報を@itemsに入れる。
    card = Card.where(user_id: current_user.id).first #cardテーブルから現在ログインしているユーザーのidを使ってカード情報を取得する
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY] #payjpの秘密鍵

    #支払い内容
    Payjp::Charge.create(
      :amount => @items.price,
      :customer => card.customer_id,
      :currency => 'jpy',
    )
    @items.update(buyer_id: current_user.id) #購入者のuser_idがitemテーブルのbuyer_idに登録される
    redirect_to action: 'done' #支払い完了ページに移動する
  end

  def done #購入完了ページ
  end

  private

  def item_params
    params.require(:item).permit(:trade_name, :description, :size, :condition, :postage, :delivery_method, :shipment_area, :shipment_date, :price, :category_parent, :category_child, :category_grandchild, :brand, images: [],
    ).merge(user_id: current_user.id, seller_id: current_user.id)
  end

  def delete_params
    params.require(:item).permit(:trade_name, :description, :size, :condition, :postage, :delivery_method, :shipment_area, :shipment_date, :price, :category_parent, :category_child, :category_grandchild, :brand, images: [],image_id:[],
    ).merge(user_id: current_user.id, seller_id: current_user.id)
  end

end

app/views/items/_banner.html.haml
.banner__container
  .banner__container--left
    .first_title
      スマホでかんたんフリマアプリ
    .second_title
      今すぐ無料ダウンロード！
    .icons
      .mercai_icon
        = image_tag 'mercari_squar.png', size:'68x68', class: 'mercari_icon'
      .app
        = image_tag 'apple.png', size:'144x40', class: 'app'
      .google
        = image_tag 'google.png', size:'144x40', class: 'google'
  .banner__container--right
    .image
      = image_tag "banner_free.png", size:'300x260', class: 'image'

app/views/items/_error_message.html.haml
-# -if model.errors.any? 
-#   .error-msg
-#     %ul
-#       -model.errors.full_messages.each do |message| 
-#         %li= message

app/views/items/_footer.html.haml
.footer__container
  .footer__container__contents
    .top_area
      %h2.style_headline
        メルカリについて
      %ul.content
        %li.list
          会社概要（運営会社）
        %li.list
          採用情報
        %li.list
          プレスリリース
        %li.list
          公式ブログ
        %li.list
          メルカリロゴ利用ガイドライン
        %a.logo
          =fa_icon 'twitter', class: 'icon'
        %a.logo
          =fa_icon 'facebook-square', class: 'icon'
    .top_area
      %h2.style_headline
        ヘルプ＆ガイド
      %ul.content
        %li.list
          メルカリガイド
        %li.list
          らくらくメルカリ便
        %li.list
          ゆうゆうメルカリ便
        %li.list
          大型メルカリ便
        %li.list
          車体取引ガイド
        %li.list
          メルカリあんしん・あんぜん宣言！
        %li.list
          偽ブランド品撲滅への取り組み
        %li.list
          メルカリボックス
    .middle_area
      %h2.style_headline
        プライバシーと利用規約
      .contents
        %ul.content
          %li.list
            プライバシーポリシー
          %li.list
            メルカリ利用規約
          %li.list
            あんしんスマホサポート制度に関する利用規約
          %li.list
            コンプライアンスポリシー
      .contents
        %ul.content
          %li.list
            個人データの安全管理に係る基本方針
          %li.list
            特定商取引に関する表記
          %li.list
            資金決済法に基づく表示
          %li.list
            法令順守と犯罪防止のために
    .end_area
      %h2.style_headline
        国
      %ul.country_content
        %li.countries
          %a.country
            日本
          %a.country
            United States
  .footer__container__logo
    %a.mercari_logo
      = image_tag 'mercari_white.png',size:'124x33', class: 'mercari_logo'
    %span.mercari_moji
      © 2019 Mercari

app/views/items/_main-contents.html.haml
.main-contents-container
  - if @items.present?
    .main-contents-container-name
      新着アイテム
    = render @items

app/views/items/_main-contents_only_appliances.html.haml
.main-contents-container
  - if @appliances.present?
    .main-contents-container-category
      家電・スマホ・カメラの商品一覧
    = render @appliances

app/views/items/_main-contents_only_hobby.html.haml
.main-contents-container
  - if @hobby.present?
    .main-contents-container-category
      おもちゃ・ホビー・グッズの商品一覧
    = render @hobby

app/views/items/_main-contents_only_mens.html.haml
.main-contents-container
  - if @mens.present?
    .main-contents-container-category
      メンズの商品一覧
    = render @mens

app/views/items/_main-contents_only_supreme.html.haml
.main-contents-container
  - if @supreme.present?
    .main-contents-container-category
      シュプリーム商品一覧
    = render @supreme

app/views/items/appliances.html.haml
.wrapper
  .main-header-appliances
    = render 'items/sub-main-header'
  .pankuzu-category
    - breadcrumb :appliances
    = breadcrumbs pretext: "",separator: " &rsaquo; "
  .main-contents
    = render 'main-contents_only_appliances'
  .sell-btn
    = render 'sell-btn'
  .banner
    = render 'banner'
  .footer
    = render 'footer'

app/views/items/buy.html.haml
.wrapper_show_buy_shimo

  = render 'devise/registrations/header-signup'

  .show__buy__container
    %section.buy__check
      %h2.buy__check__header
        購入内容の確認
      %section.buy__check__container
        .buy__check__container__item
          - if @items.images.attached?
            - @items.images.first(1).each do |image|
              = image_tag image, size: '80x80'
          %p.item__name
            = @items.trade_name
          %form.item__pricearea
            %p.item__price
              = price_jpy(@items.price)
              %span.including_postage
                送料込み
            %ul.have__pointarea
              .have__pointarea__msg__nothing
                ポイントはありません
            %ul.payment
              %li.payment__area
                .payment__area--left
                  支払い金額
                .payment__area--right
                  %span.payment__area--right__pay
                  = price_jpy(@items.price)
            %button.buy-btn
              = link_to "購入する", pay_item_path, class: 'buy-btn__red', method: :post
      %section.buy__user__container1
        .buy__user__container1__info
          %h3.buy__user__container1__info__text
            配送先
          %address.buy__user__container1__info__content
            = "〒#{@buyer.postal_cord}"
            %br
            = @prefecture_name
            = @buyer.city
            %br
            = @buyer.block
            = @buyer.building
            %br
            = @buyer.last_name
            = @buyer.first_name
          %link_to.changearea
            %span.change__link
              変更する
            = fa_icon 'angle-right', class: 'icon-right'
      %section.buy__user__container2
        .buy__user__container1__info
          %h3.buy__user__container1__info__text
            支払い方法
          - if @default_card_information.blank? #カード情報が@default~に入っていなければカード情報は表示されない
            %br /
          - else #カード情報が入っていれば表示される
            = "**** **** ****" + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          %br
            = image_tag '0192_visa.png', size: '49x15', class: 'card_icon'
          %link_to.changearea
            %span.change__link
              変更する
            = fa_icon 'angle-right', class: 'icon-right'



  = render 'devise/registrations/footer-signup'

app/views/items/hobby.html.haml
.wrapper
  .main-header-hobby
    = render 'items/sub-main-header'
  .pankuzu-category
    - breadcrumb :hobby
    = breadcrumbs pretext: "",separator: " &rsaquo; "
  .main-contents
    = render 'main-contents_only_hobby'
  .sell-btn
    = render 'sell-btn'
  .banner
    = render 'banner'
  .footer
    = render 'footer'

app/views/items/ladies.html.haml
.wrapper
  .main-header-ladies
    = render 'items/sub-main-header'
  .pankuzu-category
    - breadcrumb :ladies
    = breadcrumbs pretext: "",separator: " &rsaquo; "
  .main-contents
    = render 'main-contents_only_ladies'
  .sell-btn
    = render 'sell-btn'
  .banner
    = render 'banner'
  .footer
    = render 'footer'

app/views/items/mens.html.haml
.wrapper
  .main-header-mens
    = render 'items/sub-main-header'
  .pankuzu-category
    - breadcrumb :mens
    = breadcrumbs pretext: "",separator: " &rsaquo; "
  .main-contents
    = render 'main-contents_only_mens'
  .sell-btn
    = render 'sell-btn'
  .banner
    = render 'banner'
  .footer
    = render 'footer'