config/routes.rb
Rails.application.routes.draw do

  root to: 'items#index'
  devise_for :users,
  controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'mypage/identification', action: :edit, controller: 'identification'
  get 'mypage/profile', action: :edit, controller: 'profile'
  get "logout" => "profile#logout"
  get 'mypage' => 'profile#mypage'
  resources :items, only: [:index,:new,:show,:create,:edit,:update,:destroy] do
    get 'buy', on: :member #on: :memberでidをURLに表示させる。そのidを元にparams[:id]で情報をテーブルから引き出す。
    post 'pay', on: :member
    collection do
      get 'search'
      get 'done', to: 'items#done'
      get 'ladies'
      get 'mens'
      get 'appliances'
      get 'hobby'
      get 'chanel'
      get 'louis_vuitton'
      get 'supreme'
      get 'nike'
    end
  end

  #ユーザー各種新規登録画面
  get "signup", to: "signup#index"
  resources :signup do
    collection do
      get 'registration' #新規会員登録入力画面（userテーブルに登録したい情報）
      post 'sms_confirmation' #携帯電話番号の入力（addressテーブルに登録したい情報）
      post 'address'   #お届け先住所の入力（addressテーブルに登録したい情報）最後の入力ページ
      post 'credit_card'  #クレジットカード
      get 'done' #登録完了
    end
  end

  #マイページのお支払い方法
  resources :card, only: [:new, :show] do
    collection do
      get 'add_card', to: 'card#add_card'
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  get "categories", to: "categories#index"

  get '/jquerytest/test' => 'jquerytest#test' #jquery動作確認のためのページ
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    card = Card.where(user_id: current_user.id) #cardモデルからcurrent_user.id=user_idに当てはまるレコードがあるか
    redirect_to action: "show" if card.exists? #すでに同じuser_idのcardが存在（exists）するならshowアクションに飛ぶ
  end

  def pay
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY] #テスト秘密鍵の環境変数
    if params['payjp-token'].blank? #pyajp-tokenが空または存在しないか判定している（blank?はnilと空のオブジェクトを判定できる）
      redirect_to action: "add_card" #もしpayjp-tokenが空（未入力？）ならnewアクションへ飛ぶ
    else
      customer = Payjp::Customer.create(  #payjp::Customer.createで顧客作成→()の情報で作成されたトークンを用いて顧客情報を導入している？
        email: current_user.email,
        card: params['payjp-token'], #入力されたpayjp-token（params）を持ったcard
        metadata: {user_id: current_user.id} #user_id=current_user.idのメタデータ
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show" #cardが保存できたらshowアクションへ飛ぶ
      else
        redirect_to action: "pay" #保存できなかったらpayアクションやり直し
      end
    end
  end

  def delete
    card = Card.where(user_id: current_user.id).first #該当するuser_idのカードテーブルの最初の一件
    if card.blank? #カードは空または存在しているか判定している
    else #カードが存在するなら
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY] #テスト秘密鍵
      customer = Payjp::Customer.retrieve(card.customer_id) #retrieve（翻訳：取り戻す）が調べてもわからず
      customer.delete #作成した顧客を削除
      card.delete #カードも削除
    end
      redirect_to action: "add_card" #カードが存在しなくなったらnewアクションへ飛ぶ
  end

  def show
    card = Card.where(user_id: current_user.id).first #該当するuser_idのカードテーブルの最初の一件
    if card.blank? #カードは空または存在しているか判定している
      redirect_to action: "add_card" #空ならnewへ飛ぶ
    else #存在している場合は秘密鍵をつかってPayjpから情報を引っ張ってきて表示する。
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY] #テスト秘密鍵
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def add_card
  end
end

app/views/card/_mypage_card_new.html.haml
= form_tag(pay_card_index_path, method: :post, id: 'charge-form', name: "inputForm") do
  %label カード番号
  = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ", maxlength: "16",type: "text", id: "card_number"
  %br
  %label 有効期限
  %select#exp_month{name: "exp_month", type: "text"}
    %option{value: ""} --
    %option{value: "1"}01
    %option{value: "2"}02
    %option{value: "3"}03
    %option{value: "4"}04
    %option{value: "5"}05
    %option{value: "6"}06
    %option{value: "7"}07
    %option{value: "8"}08
    %option{value: "9"}09
    %option{value: "10"}10
    %option{value: "11"}11
    %option{value: "12"}12
  %span 月/
  %select#exp_year{name: "exp_year", type: "text"}
    %option{value: ""} --
    %option{value: "2019"}19
    %option{value: "2020"}20
    %option{value: "2021"}21
    %option{value: "2022"}22
    %option{value: "2023"}23
    %option{value: "2024"}24
    %option{value: "2025"}25
    %option{value: "2026"}26
    %option{value: "2027"}27
    %option{value: "2028"}28
    %option{value: "2029"}29
  %span 年
  %br
  %label セキュリティコード
  = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
  #card_token
  = submit_tag "追加する", id: "token_submit"

app/views/card/add_card.html.haml
.wrapper-creditcard_kiji
  .main-header-add_card
    = render 'items/sub-main-header'
  .pankuzu-add_card
    - breadcrumb :card
    = breadcrumbs pretext: "",separator: " &rsaquo; "

  .mypage_container_kiji
    .mypage__container
      .credit-card
        %h2.credit-card__header
          支払い方法
        .credit-card__form
          .credit-card__form__content
            %p クレジットカード一覧
            .credit-card__form__content__add_btn
              = link_to 'クレジットカードを追加する', new_card_path, class:'default_btn_red'
              %i.material-icons.md-36 credit_card
        .credit-card__link
          %p.link_text 支払い方法について ＞
    .mypage-left
      = render 'profile/mypage-left'
  .banner
    = render 'items/banner'
  .fotter  
    = render 'items/footer'

app/views/card/new.html.haml
.wrapper-creditcard-shimo
  .main-header-new_card
    = render 'items/sub-main-header'
  
  .pankuzu-new_card
    - breadcrumb :card
    = breadcrumbs pretext: "",separator: " &rsaquo; "

  .mypage_container_shimo
    .mypage__container
      .credit-card
        %h2.credit-card__header
          クレジットカード情報入力
        .credit-card__form
          = form_tag(pay_card_index_path, method: :post, id: 'charge-form', name: "inputForm") do
            .credit-card__form__content
              .credit-card__form__content__numberarea
                %label.card_label
                  カード番号
                %span.required
                  必須
                = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ", maxlength: "16",type: "text", id: "card_number"
                %ul.card_list_area
                  %li.card_list_first
                    = image_tag 'visa.png', size: '49x35', class: 'card_icon'
                  %li.card_list
                    = image_tag 'master.png', size: '34x20', class: 'card_icon'
                  %li.card_list
                    = image_tag 'saisoncard.png', size: '30x20', class: 'card_icon'
                  %li.card_list
                    = image_tag 'jcb.png', size: '32x20', class: 'card_icon'
                  %li.card_list
                    = image_tag 'amex.png', size: '21x20', class: 'card_icon'
                  %li.card_list
                    = image_tag 'diners.png', size: '32x20', class: 'card_icon'
                  %li.card_list
                    = image_tag 'discover.png', size: '32x20', class: 'card_icon'
              .credit-card__form__content__validityarea
                %label.card_label
                  有効期限
                %span.required
                  必須
                %br
              .credit-card__form__content__validityarea__select-left
                %select#exp_month{name: "exp_month", type: "text"}
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                %i.choose__wrap
                  = fa_icon 'angle-down', class: 'icon-down'
                %span.mm
                  月
              .credit-card__form__content__validityarea__select-right
                %select#exp_year{name: "exp_year", type: "text"}
                  %option{value: ""} --
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                %i.choose__wrap
                  = fa_icon 'angle-down', class: 'icon-down'
                %span.yy
                  年
              %ul.wrapper-error
              .credit-card__form__content__securitycordarea
                %label.card_label
                  セキュリティーコード
                %span.required
                  必須
                = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
                %ul.wrapper-error
                .what_cord
                  .what_cord__msg
                    %span.question
                      ?
                    %link_to.question_msg
                      カード裏面の番号とは?
              #card_token
              = submit_tag "追加する", id: "token_submit", class: "add-btn"

    .mypage-left
      = render 'profile/mypage-left'
  .banner
    = render 'items/banner'
  .fotter  
    = render 'items/footer'




















-# .wrapper-creditcard-shimo
-#   .main-header
-#     = render 'items/main-header'

-#   .mypage_container_shimo
-#     .mypage__container
-#       .credit-card
-#         %h2.credit-card__header
-#           クレジットカード情報入力
-#         .credit-card__form
-#           .credit-card__form__content
-#             .credit-card__form__content__numberarea
-#               %label.card_label
-#                 カード番号
-#               %span.required
-#                 必須
-#               %input.credit-card__form__content__numberarea__pay_no{placeholder: '半角数字のみ', type: 'number', maxlength: '19'}
-#               %ul.card_list_area
-#                 %li.card_list_first
-#                   = image_tag 'visa.png', size: '49x35', class: 'card_icon'
-#                 %li.card_list
-#                   = image_tag 'master.png', size: '34x20', class: 'card_icon'
-#                 %li.card_list
-#                   = image_tag 'saisoncard.png', size: '30x20', class: 'card_icon'
-#                 %li.card_list
-#                   = image_tag 'jcb.png', size: '32x20', class: 'card_icon'
-#                 %li.card_list
-#                   = image_tag 'amex.png', size: '21x20', class: 'card_icon'
-#                 %li.card_list
-#                   = image_tag 'diners.png', size: '32x20', class: 'card_icon'
-#                 %li.card_list
-#                   = image_tag 'discover.png', size: '32x20', class: 'card_icon'
-#             .credit-card__form__content__validityarea
-#               %label.card_label
-#                 有効期限
-#               %span.required
-#                 必須
-#               %br
-#               .credit-card__form__content__validityarea__select-left
-#                 %select{:name => "mm"}
-#                   %option{:value => "01"} 01
-#                   %option{:value => "02"} 02
-#                   %option{:value => "03"} 03
-#                   %option{:value => "04"} 04
-#                   %option{:value => "05"} 05
-#                   %option{:value => "06"} 06
-#                   %option{:value => "07"} 07
-#                   %option{:value => "08"} 08
-#                   %option{:value => "09"} 09
-#                   %option{:value => "10"} 10
-#                   %option{:value => "11"} 11
-#                   %option{:value => "12"} 12
-#                 %i.choose__wrap
-#                   = fa_icon 'angle-down', class: 'icon-down'
-#                 %span.mm
-#                   月
-#               .credit-card__form__content__validityarea__select-right
-#                 %select{:name => "yy"}
-#                   %option{:value => "19"} 19
-#                   %option{:value => "20"} 20
-#                   %option{:value => "21"} 21
-#                   %option{:value => "22"} 22
-#                   %option{:value => "23"} 23
-#                   %option{:value => "24"} 24
-#                   %option{:value => "25"} 25
-#                   %option{:value => "26"} 26
-#                   %option{:value => "27"} 27
-#                   %option{:value => "28"} 28
-#                   %option{:value => "29"} 29
-#                 %i.choose__wrap
-#                   = fa_icon 'angle-down', class: 'icon-down'
-#                 %span.yy
-#                   年
-#               %ul.wrapper-error
-#             .credit-card__form__content__securitycordarea
-#               %label.card_label
-#                 セキュリティーコード
-#               %span.required
-#                 必須
-#               %input.credit-card__form__content__securitycordarea__cord_no{placeholder: 'カード背面4桁もしくは3桁の番号', type: 'number'}
-#               %ul.wrapper-error
-#               .what_cord
-#                 .what_cord__msg
-#                   %span.question
-#                     ?
-#                   %link_to.question_msg
-#                     カード裏面の番号とは?
-#             %button.add-btn
-#               追加する

-#     .mypage-left
-#       = render 'profile/mypage-left'
-#   .banner
-#     = render 'items/banner'
-#   .fotter  
-#     = render 'items/footer'

app/views/card/show.html.haml
.wrapper-credit_card_show-kiji
  .main-header-credit_card
    = render 'items/sub-main-header'
  .pankuzu-show_card
    - breadcrumb :card
    = breadcrumbs pretext: "",separator: " &rsaquo; "
  .mypage_container_kiji
    .mypage__container
      .credit-card
        %h2.credit-card__header
          支払い方法
        .credit-card__form
          .credit-card__form__content
            %p クレジットカード一覧
            .show_card_info
              = "**** **** **** " + @default_card_information.last4
              %br
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
              = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
                %input{ type: "hidden", name: "card_id", value: "" }
                %button.delete_btn 削除する
        .credit-card__link
          %p.link_text 支払い方法について ＞

    .mypage-left
      = render 'profile/mypage-left'
  .banner
    = render 'items/banner'
  .fotter  
    = render 'items/footer'


-# 登録したクレジットカードを表示する時の記述
-# 参考として残したいです。
-# .show_card_info
-#   %label 登録クレジットカード情報
-#   %br
-#   = "**** **** **** " + @default_card_information.last4
-#   %br
-#   - exp_month = @default_card_information.exp_month.to_s
-#   - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
-#   = exp_month + " / " + exp_year
-#   = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
-#     %input{ type: "hidden", name: "card_id", value: "" }
-#     %button 削除する